nixos/sshd: Allow UsePAM being null
This commit allows setting the `UsePAM` setting to null. Without it, nix
fails with:
```
error: ‘mkIf’ called with a non-Boolean condition
```

Setting it to null means no line for `UsePAM` is written into the
resulting sshd config file. This is needed if openssh is compiled
without PAM support. Otherwise the following error message is produced:
```
rexec line 15: Unsupported option UsePAM
```